### ISSUE TITLE
Links between tips and taxa, what's changed?

### ISSUE THREAD

**Issue by rvosa** [MesquiteProject/MesquiteCore#39]
Hi all,

I tested whether the nexml reader still works in mesquite 3.x but unfortunately it no longer does. Something has changed about the API but I don't quite know what. The problem is in reading trees from nexml and correctly linking the tips in the trees up to the taxa (which we've already read). For some reason the tree window now goes garbled, and the log shows: `error: negative taxon number found in DrawNamesTreeDisplay -1  tree: `. What's changed, and how do I catch up again?

Thanks,

Rutger

**Comment by wmaddisn** [comment]
I had thought that all the changes would have moved toward greater permissiveness.  Does this apply for any tree?  Could you send me a very simple example?

Wayne
 
On 19 Jul 2015, at 8:17, Rutger Vos <notifications@github.com> wrote:

> Hi all,
> 
> I tested whether the nexml reader still works in mesquite 3.x but unfortunately it no longer does. Something has changed about the API but I don't quite know what. The problem is in reading trees from nexml and correctly linking the tips in the trees up to the taxa (which we've already read). For some reason the tree window now goes garbled, and the log shows: error: negative taxon number found in DrawNamesTreeDisplay -1 tree:. What's changed, and how do I catch up again?
> 
> Thanks,
> 
> Rutger
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--------------
Wayne Maddison
Professor and Canada Research Chair, Depts. of Zoology and Botany
6270 University Boulevard
University of British Columbia
Vancouver, BC  V6T 1Z4   Canada

Lab web page: http://waynemaddisonlab.wordpress.com
Mesquite: http://mesquiteproject.wikispaces.com; MacClade: http://macclade.org
Beaty Biodiversity Museum: http://beatymuseum.ubc.ca

**Comment by rvosa** [comment]
Hi Wayne,

I found it. I was trying to read a nexml file from [phylomatic](https://github.com/camwebb/phylomatic-ws) but I didn't expect this to include higher taxa - or put the other way: internal nodes referencing OTUs. The nexml spec allows that but it is a bit at odds with the MesquiteTree, which only allows tips to link to taxa. 

The "fix" is that we now just copy over the higher taxon name to the node label. This way we don't force @camwebb to use just node labels for higher taxa, so that at a later date he can attach more metadata to it. This now works as of commit https://github.com/nexml/nexml.java/commit/6f6a0c922910c5411470b2d6a264243ceb0f9135, so this issue can be closed.

Thanks for thinking along!

Rutger
