### ISSUE TITLE
Link to Mesquite 3.04 (build 725) LINUX not working

### ISSUE THREAD

**Issue by drelo** [MesquiteProject/MesquiteCore#41]
Hi, the link to download the latest linux version is not working, it takes you to a WIN version.
I don't know how to compile using the source as provided here so I would need that Linux version or some instructions to compile it. Thanks in advance
best regards,
Andres

**Comment by wmaddisn** [comment]
Sorry!  Link fixed.  Does it work for you now?
Wayne

> On 19 Aug 2015, at 12:45, drelo <notifications@github.com> wrote:
> 
> Hi, the link to download the latest linux version is not working, it takes you to a WIN version.
> I don't know how to compile using the source as provided here so I would need that Linux version or some instructions to compile it. Thanks in advance
> best regards,
> Andres
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------
Wayne Maddison
Professor and Canada Research Chair, Depts. of Zoology and Botany
6270 University Boulevard
University of British Columbia
Vancouver, BC  V6T 1Z4   Canada

Lab web page: http://waynemaddisonlab.wordpress.com
Mesquite: http://mesquiteproject.wikispaces.com; MacClade: http://macclade.org
Beaty Biodiversity Museum: http://beatymuseum.ubc.ca

**Comment by drelo** [comment]
It worked! Thanks again.
Andrés
