### ISSUE TITLE
3.04 not working with Java 9

### ISSUE THREAD

**Issue by drelo** [MesquiteProject/MesquiteCore#42]
Hi, I installed Oracle Java following[ these instructions](http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html) and I got this version but when I try to run it I got a message it need Java 6 or higher, it seems in these machine it's not recognizing it. How can I fix it? Thanks for your help

I am using Ubuntu 15.10 and got this Java installed

→ java -version 
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+102-2016-01-21-001533.javare.4316.nc)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+102-2016-01-21-001533.javare.4316.nc, mixed mode)

**Comment by drelo** [comment]
Just to add this is the message given in the console

Note: (Mesquite): This version of Mesquite requires Java 1.6 or higher.  Please update your version of Java, or use an older version of Mesquite.  Please be aware however that earlier versions of Mesquite may have bugs that affect your results.  Please check the Mesquite website for information.
Dialog box shown.  Title: Note

**Comment by wmaddisn** [comment]
Thank you for telling us about this.  We will look into it.

Do you need to use Java 9?  It’s not yet officially supported by Oracle.

Wayne

> On 9 Mar 2016, at 09:34, Andres Parada <notifications@github.com> wrote:
> 
> Just to add this is the message given in the console
> 
> Note: (Mesquite): This version of Mesquite requires Java 1.6 or higher. Please update your version of Java, or use an older version of Mesquite. Please be aware however that earlier versions of Mesquite may have bugs that affect your results. Please check the Mesquite website for information.
> Dialog box shown. Title: Note
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------
Wayne Maddison
Professor and Canada Research Chair, Depts. of Zoology and Botany
6270 University Boulevard
University of British Columbia
Vancouver, BC  V6T 1Z4   Canada

Lab web page: http://waynemaddisonlab.wordpress.com
Mesquite: http://mesquiteproject.wikispaces.com; MacClade: http://macclade.org
Beaty Biodiversity Museum: http://beatymuseum.ubc.ca

**Comment by drelo** [comment]
No, no particular reason, I didn't know if it was supported. I just configured a new machine and saw the option of going into 9 during those instructions.  I just went back to 8 and it worked fine. Thanks for your help!

**Comment by drelo** [comment]
No, no particular reason, I didn't know if it was supported. I just
configured a new machine and saw the option of going into 9 during those
instructions.  I just went back to 8 and it worked fine. *Thanks for your
help!*

2016-03-09 16:12 GMT-03:00 Wayne Maddison <notifications@github.com>:

> Thank you for telling us about this. We will look into it.
>
> Do you need to use Java 9? It’s not yet officially supported by Oracle.
>
> Wayne
>
> > On 9 Mar 2016, at 09:34, Andres Parada <notifications@github.com>
> wrote:
> >
> > Just to add this is the message given in the console
> >
> > Note: (Mesquite): This version of Mesquite requires Java 1.6 or higher.
> Please update your version of Java, or use an older version of Mesquite.
> Please be aware however that earlier versions of Mesquite may have bugs
> that affect your results. Please check the Mesquite website for
> information.
> > Dialog box shown. Title: Note
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> --------------
> Wayne Maddison
> Professor and Canada Research Chair, Depts. of Zoology and Botany
> 6270 University Boulevard
> University of British Columbia
> Vancouver, BC V6T 1Z4 Canada
>
> Lab web page: http://waynemaddisonlab.wordpress.com
> Mesquite: http://mesquiteproject.wikispaces.com; MacClade:
> http://macclade.org
> Beaty Biodiversity Museum: http://beatymuseum.ubc.ca
>
>
>
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MesquiteProject/MesquiteCore/issues/42#issuecomment-194458125>
> .
>



-- 
Postdoctoral Associate

Instituto de Cs Ambientales y Evolutivas
Universidad Austral de Chile
Campus Isla Teja s/n
Valdivia, Chile
